### ISSUE TITLE
Discussion: Präsenzbestand / in presentation

### ISSUE THREAD

**Issue by LeAchim59** [Larian77/Openbiblio#13]
Es gibt Exemplare, die im Bestand vorhanden sind, auch öffentlich zugänglich sind, aber nicht ausgeliehen werden sollen. Der Präsenzbestand.
Derzeit kann man bei einem Exemplar (biblio_copy) den Status auf "in Präsentation" setzen. Dieser verhindert aber nicht die Ausleihe.
Je nachdem, wie die Sammlung räumlich organisiert ist, betrifft das auch den Standort des Exemplars. 

Lösungsvorschlag:
- Auf jeden Fall entweder den Status "in Präsentation" in der Wirkung ändern oder einen neuen Status für das Exemplar einführen. Dieser verhindert die Ausleihe und Reservierung.
- Für neuen Statuswert spricht, kann man auch ohne Änderung der Datenbankstruktur einführen und würde Bestandsdaten nicht im Verhalten verändern.
- bisher gibt es kein Feld "Standort des Exemplars", das kann aber unabhängig von dieser Lösung eingeführt werden. #14 

---
There are items that are available in the collection and are also accessible to the public, but are not to be borrowed. The reference collection.
You can currently set the status of a copy (biblio_copy) to "in presentation". However, this does not prevent items from being borrowed.
Depending on how the collection is spatially organised, this also affects the location of the copy. 

Suggested solution:
- In any case, either change the "in presentation" status in the effect or introduce a new status for the item. This prevents borrowing and reservation.
- The new status value can also be introduced without changing the database structure and would not change the behaviour of stock data.
- So far there is no field "Location of copy", but this can be introduced independently of this solution. 

Translated with DeepL.com (free version)

**Comment by Larian77** [comment]
Die derzeitige Lösung wäre eine Medienart "Präsentation" zu erstellen, wo man dann definieren könnte, dass diese nicht ausgeliehen werden kann. Aber grundsätzlich sollte für eine zukünftige Version tatsächlich darüber nachgedacht werden.

The current solution would be to create a media type "Presentation", where you could define that it cannot be borrowed. But in principle, this should really be considered for a future version.

**Comment by LeAchim59** [comment]
Richtig, die Medienart kann nicht die Lösung sein. Die beschreibt das Medium und nicht den Umgang damit und wir haben durchaus auch mehrere Exemplare des gleichen Mediums, von denen einige ausgeliehen und ein anderes in Präsentation sein kann.
Ich sehe kein Hindernis (außer zeitlich), warum man das nicht in der derzeitigen DB Version implementieren kann. Es ist lediglich die Einführung eines neuen Status für ein Exemplar, der nur manuell gesetzt werden kann. Wer ihn nicht nutzt, für den verändert sich nichts.

---
Correct, the type of media cannot be the solution. It describes the medium and not the handling of it, and we may well have several copies of the same medium, some of which may be on loan and another in presentation.
I see no obstacle (other than time) as to why this cannot be implemented in the current DB version. It is just the introduction of a new status for a copy, which can only be set manually. For those who do not use it, nothing changes.
