### ISSUE TITLE
Installationsanleitung aktualisieren

### ISSUE THREAD

**Issue by speedy-10** [Larian77/Openbiblio#22]
Hallo zusammen,
wäre es möglich, die Installationsanleitung so zu aktualisieren, dass man die aktuellste Openbiblio-Version installieren kann?

VG

**Comment by Larian77** [comment]
Im Git kannst du dir die aktuellste Betaversion (unter Releases) herunterladen. Hier hast du auch eine aktualisierte Installationsanleitung schon dabei, wobei sich hier nicht viel ändert.
Auf der Openbiblio-Seite selber aktualisiere ich alles erst, wenn es eine offizielle neue Version gibt :-)
