### ISSUE TITLE
Hilfe zur Erstinstallation von Openbiblio 0.8beta

### ISSUE THREAD

**Issue by speedy-10** [Larian77/Openbiblio#26]
Hallo zusammen,
zum Testen habe ich eine VM von LinuxMint 21.3 aufgesetzt.
Dort nach der Anleitung www.apachefriends.org/faq_linux.html:
- Xamp installiert: ```sudo ./xampp-linux-x64-8.2.4-0-installer.run```
- im Terminal ausgeführt: ```mysql -uroot mysql```
Meldung:
```
~/Downloads$ mysql -uroot mysql
Der Befehl 'mysql' wurde nicht gefunden, kann aber installiert werden mit:
sudo apt install mysql-client-core-8.0     # version 8.0.35-0ubuntu0.22.04.1, or
sudo apt install mariadb-client-core-10.6  # version 1:10.6.12-0ubuntu0.22.04.1
```
```
~/Downloads$ sudo apt install mariadb-client-core-10.6  # version 1:10.6.12-0ubuntu0.22.04.1
#...
~/Downloads$ mysql -uroot mysql
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
```
System:
```
Kernel: 5.15.0-101-generic x86_64 bits: 64 Desktop: Cinnamon 6.0.4 Distro: Linux Mint 21.3 Virginia
```

Wie komme ich hier weiter?

VG

**Comment by Larian77** [comment]
Bitte keine Programm-Issues aufmachen, wenn es nichts mit dem Programm zu tun hat :-) - dazu gerne die Diskussions nutzen
Das Problem, was du hier hast, ist noch vor dem Programm auf der Kommandozeilenebene.
Warum benutzt du unter Linux ein XAMPP?

Bitte direkt mysql, php und apache installieren :-)

Mit XAMPP unter Linux kann ich leider nicht weiterhelfen. Zur allgemeinen Installation von LAMP unter Mint gibt es z.B. hier ein Tutorial:
https://techviewleo.com/how-to-install-lamp-stack-on-linux-mint/?utm_content=cmp-true
