### ISSUE TITLE
Blank report print pages

### ISSUE THREAD

**Issue by fb4thxUall** [Larian77/Openbiblio#32]
Hi,

vielen Dank für das Update auf 0.8. Wir führen die Software gerade neu bei uns ein.

Bei mir tritt folgendes Problem auf: Egal welchen Bericht ich aufrufe, sobald ich eine Liste drucken möchte, erhalte ich eine leere Seite. Die error.logs liefern auch Aufschluss, das Problem entsteht in der Datei .../classes/Lay.php: Die Zeile 806 produziert einen Fehler über FastCGI-stderror-PHP-Message: "Call to undefined function mb_convert_encoding()" 

Verwendete Openbiblioversion: 0.8 mit database Version 0.7.1.
PHP Version 8.1.2-1ubuntu2.15

Genaue Fehlermeldung:
`2024-04-19 16:59:12: (mod_fastcgi.c.451) FastCGI-stderr:PHP message: PHP Warning:  Undefined variable $lookup in /var/www/html/Openbiblio/navbars/opac.php on line 15
2024-04-19 17:01:13: (mod_fastcgi.c.451) FastCGI-stderr:PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/html/Openbiblio/classes/Lay.php:806
2024-04-19 17:01:13: (mod_fastcgi.c.451) FastCGI-stderr:Stack trace:
2024-04-19 17:01:13: (mod_fastcgi.c.451) FastCGI-stderr:#0 /var/www/html/Openbiblio/layouts/default/list.php(45): Lay->text()
2024-04-19 17:01:13: (mod_fastcgi.c.451) FastCGI-stderr:#1 /var/www/html/Openbiblio/shared/layout.php(69): Layout_list->render()
2024-04-19 17:01:13: (mod_fastcgi.c.451) FastCGI-stderr:#2 {main}
2024-04-19 17:01:13: (mod_fastcgi.c.451) FastCGI-stderr:  thrown in /var/www/html/Openbiblio/classes/Lay.php on line 806
`

Herzlichen Dank
fb4thxUall

**Comment by 375michael40veit** [comment]
Bitte ändere den Code in Zeile 806 von 
`$text = iconv('UTF-8', 'ASCII//IGNORE', mb_convert_encoding($outputString ?? '', 'UTF-8'));`
in 
`$text = iconv('UTF-8', 'ISO-8859-1//IGNORE', mb_convert_encoding($outputString ?? '', 'UTF-8'));`

Dies sollte Dein Problem lösen, zumindest hat es bei mir das Problem beim Erstellen von pdf-Dateien gelöst.
Eine kurze Rückmeldung, ob dies auch bei Dir das Problem löst, wäre super.

**Comment by fb4thxUall** [comment]
Hi, vielen Dank für deine schnelle Reaktion. Ich habe das geändert, die Änderung wurde auch übernommen und ausgeführt. Allerdings bleibt die Seite genauso leer wie vorher und auch die Fehlermeldung ist exakt identisch zu vorher. Kann ich hilfreiche Infos liefern?

Vielen Dank für die Mühe
fb4thxUall

**Comment by 375michael40veit** [comment]
Hallo, 
folgende Fehlermeldung "Uncaught Error: Call to undefined function mb_convert_encoding()" könnte ein Hinweis sein, dass die php-extension mbstring nicht installiert oder in der php.ini nicht aktiviert ist.
Die installierten Module kann man mit phpinfo() abrufen und nachsehen, ob mbstring enable ist. Dies kann bspw. über eine eigene phpinfo.php-Datei sein, die folgenden Code enthalten soll:
```
<?php
     phpinfo();
?>
```

**Comment by Larian77** [comment]
@fb4thxUall danke fürs Melden
@375michael40veit vielen Dank für den Fix und die Erklärung des Ganzen (und die anderen Fixes)
Pull-Request ist im Main-Branch, würde noch ne Woche warten und dann Anfang nächster Woche eine Bugfixing-Version releasen :-)
