### ISSUE TITLE
medien search

### ISSUE THREAD

**Issue by 375michael40veit** [Larian77/Openbiblio#33]
Von bestimmten Webseiten löst der Klick auf die Mediensuche einen fatalen Fehler aus. Eine Fehlermeldung erfolgt über die URL.

URL-Text ist: http://localhost/openbiblio/opac/index.php%3Cbr%20/%3E%3Cb%3EWarning%3C/b%3E:%20%20Undefined%20variable%20$lookup%20in%20%3Cb%3EC:[....]/openbiblio/navbars/opac.php%3C/b%3E%20on%20line%20%3Cb%3E15%3C/b%3E%3Cbr%20/%3E

Anmerkung: [...] Pfad wurde gekürzt
_____________________________________

Clicking on the media search from certain websites triggers a fatal error. An error message is displayed via the URL.

URL is: http://localhost/openbiblio/opac/index.php%3Cbr%20/%3E%3Cb%3EWarning%3C/b%3E:%20%20Undefined%20variable%20$lookup%20in%20%3Cb%3EC:[....]/openbiblio/navbars/opac.php%3C/b%3E%20on%20line%20%3Cb%3E15%3C/b%3E%3Cbr%20/%3E

Note: [...] path has been shortened

![OpBib_Medienstuche_Bug1](https://github.com/Larian77/Openbiblio/assets/3150458/d1239205-a648-40bb-b817-dbf8a5df7495)
![OpBib_Medienstuche_Bug2](https://github.com/Larian77/Openbiblio/assets/3150458/0a69676d-e481-4c4d-86b6-e74dde37a53a)

**Comment by Larian77** [comment]
@375michael40veit da im Screenshot leider nicht die undefinierte Variable zu sehen ist, ist das der Bug, den du schon in deinem Pull Request behoben hast? :-)

**Comment by 375michael40veit** [comment]
@Larian77: Undefined variable $lookup in C:[....]/openbiblio/navbars/opac.php on line 15
Der Fehler taucht nicht im eingeloggten MA-Status auf, jedoch im nicht eingeloggten Zustand, wenn man bspw. ein Medium sucht, dies näher ansieht und dann wieder auf Mediensuche geht.

**Comment by 375michael40veit** [comment]
@Larian77: Pull request-Vorschlag zur Behebung dieses Bugs --> siehe [](https://github.com/Larian77/Openbiblio/pull/36)

**Comment by Larian77** [comment]
Pullrequest integriert
