### ISSUE TITLE
Anzeige des aktuellen Anmeldenamen

### ISSUE THREAD

**Issue by schubichler1** [Larian77/Openbiblio#35]
In der Oberfläche wird anscheinend nirgends angezigt, als welcher Benutzer man gerade eingeloggt ist. 

intuitiv wäre es hier 

![grafik](https://github.com/Larian77/Openbiblio/assets/168106796/6d41647f-128e-487a-8b4b-2874cbddb6df)

oder hier
![grafik](https://github.com/Larian77/Openbiblio/assets/168106796/08810ecd-1570-4a6a-b5db-224bdb0a9090)

**Comment by 375michael40veit** [comment]
The display of the logged-in user is now shown below the login button.
More details under #87
