### ISSUE TITLE
Menüpunkt ändert den Text

### ISSUE THREAD

**Issue by reinhard-mueller** [Larian77/Openbiblio#41]
In den mehreren Navbars gibt es einen Menüpunkt für die Suche nach Medien, dieser heißt je nachdem, ob er aktiv ist oder nicht entweder "Suche" oder "Mediensuche".

Beispiel: auf der Seite catalog/index.php heißt er als aktiver Eintrag "Suche", wählt man dann den anderen Menüpunkt "Neues Medium", so ändert er seinen Text als nicht mehr aktiver Eintrag auf "Mediensuche".

Das ist etwas verwirrend, und ich bin nicht sicher, ob es einen schlüssigen Grund dafür gibt. Mein Vorschlag wäre, im gesamten Code die Loc-Variablen `catalogSearch1` und `catalogSearch2` zusammenzulegen.

**Comment by LeAchim59** [comment]
Hallo,
wahrscheinlich gibt es dafür keinen Grund, es ist nur noch nicht aufgefallen.

Michael

**Comment by Larian77** [comment]
schaue ich mir mal an, wenn wir die nächste Version haben, an der gerade gebastelt wird :)

**Comment by 375michael40veit** [comment]
Menu item has the same text now #85
