### ISSUE TITLE
Bild hochladen und anzeigen - ohne Datenbankänderung

### ISSUE THREAD

**Issue by LeAchim59** [Larian77/Openbiblio#6]
Auf MARC Field 902a wird der Name der Bilddatei zu einem Medium abgelegt und ggf. angezeigt, wenn Bild im  Order pictures vorhanden ist. Momentan muss man die Bilder per ftp hochladen und den Namen einem Medium zuweisen.

Für die bei "Darmstadt spielt daheim" eingesetzte Version habe ich folgende Erweiterung vorgenommen:

Upload eines Bildes für ein bestimmtes Medium
Anpassungen bei der Ausgabe auf Medienseite und im OPAC

catalog/upload_picture_form.php: Bild hochladen
catalog/upload_picture.php: Bild hochladen
classes/BiblioSeach.php: Erweiterung Bild
locale/de/cataloging.php: Bild hochladen
locale/de/navbars.php:: Bild hochladen
navbars/cataloging.php: Bild hochladen
shared/biblio_search.php: Formatierung der Ausgabe und Ausgabe des Bilds

Das ist nur eine sehr rudimentäre Erweiterung (mit wahrscheinlich unheimlich vielen Sicherheitslücken). Geht aber ohne Erweiterung der Datenbank. Den Code kann ich gerne zur Verfügung stellen, wenn sich den jemand anschauen will.

aber: Besser wäre eine ordentliche Bilderverwaltung, bei der man Bilder verwalten, ändern und wieder löschen kann und die sich dann den Medien zuweisen lassen.

**Comment by Larian77** [comment]
kannst ja den Code gerne mal geben zum drüber schauen :-)

**Comment by LeAchim59** [comment]
Was noch fehlt und wovon ich momentan keine Ahnung habe, wie man das macht, wäre eine Überprüfung der Bildgröße und Skaliserung auf eine vernünftige Darstellungsgröße. Momentan muss der Anwender dafür vorher manuell sorgen.

**Comment by LeAchim59** [comment]
Ich habe im neuen branch #6-upload-picture meinen Stand eingefügt. Ist noch zu überprüfen, ob PHP8-kompatibel (da weiß ich zu wenig drüber). Betroffene Dateien s.o. für local/de habe ich es auch noch eingefügt.

Wie gesagt, skalieren des Bildes wäre noch toll. Da braucht man wahrscheinlich eine zusätzliche lib.

**Comment by LeAchim59** [comment]
Zum Sklalieren bin ich hier fündig geworden;

https://www.php-einfach.de/experte/codeschnipsel/6213-bild-verkleinern-jpegpnggif/

Hier kann man es in der Anwendung sehen:
https://www.all4hardware4u.de/programmierung/codeschnipsel/bilder-skalieren-mit-php/

Vorraussetzung ist eine PHP-Umgebung mit GD.Lib.

**Comment by LeAchim59** [comment]
Zum Thema Bildupload etwas sicher machen, habe ich dort noch einen Codeschnipsel gefunden:

```
//Überprüfung der Dateigröße
$max_size = 500*1024; //500 KB
if($_FILES['datei']['size'] > $max_size) {
   die("Bitte keine Dateien größer 500kb hochladen");
}
 
//Überprüfung dass das Bild keine Fehler enthält
if(function_exists('exif_imagetype')) { //Die exif_imagetype-Funktion erfordert die exif-Erweiterung auf dem Server
   $allowed_types = array(IMAGETYPE_PNG, IMAGETYPE_JPEG, IMAGETYPE_GIF);
   $detected_type = exif_imagetype($_FILES['datei']['tmp_name']);
   if(!in_array($detected_type, $allowed_types)) {
      die("Nur der Upload von Bilddateien ist gestattet");
   }
}
```

Quelle: https://www.php-einfach.de/php-tutorial/dateiupload/

**Comment by Larian77** [comment]
So, es waren noch einige Prüfungen notwendig (leerer Dateiname, upload-max-Einstellung, ...) aber ist nun auch in der Betaversion
Damit ist 0.8 in der Entwicklung abgeschlossen und muss nur noch getestet werden

**Comment by LeAchim59** [comment]
@Larian77 Ich war zwar noch nicht ganz fertig. So kam ich nicht mehr dazu, das mit der Größenanpassung eines Bildes  zu testen. Wenn wir aber in der Anleitung angeben, die Bilder sollen 150px breit sein, kann man erst mal damit leben.
