### ISSUE TITLE
0.8.1 new member error if library settings are Online access for users is unchecked

### ISSUE THREAD

**Issue by sarangtc** [Larian77/Openbiblio#62]
**To recreate:**
disable "Online access for users" in Admin > Library Settings

**Behaviour:**
Password creation by e-mail? 
Password:
Repeat password:
fields are not shown in new member form

and 

When form is submitted (might need php error checking enabled), get the following error
```
Warning: Undefined array key "TypeOfPwdCreation" in /var/www/html/openbiblio/circ/mbr_new.php on line 50

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/openbiblio/circ/mbr_new.php:50) in /var/www/html/openbiblio/circ/mbr_new.php on line 96
```

Need to handle this case properly

**Comment by Larian77** [comment]
@375michael40veit kann ich nachvollziehen, er meckert bei leerer Mail auch dass die Mail nicht korrekt wäre - das müssen wir noch fixen - heute wirds bei mir nichts mehr, ich schaue sonst nächste Woche mal

**Comment by 375michael40veit** [comment]
@sarangtc @Larian77 
As far as you haven't fixed it yet, I can have a look at it in two weeks when I have more time.

**Comment by 375michael40veit** [comment]
Fehler behoben: Keine Kennwort-Validierung, wenn Online-Zugang für Nutzer nicht aktiviert ist.

Wann soll es möglich sein, dass auch keine E-Mail-Adresse hinterlegt wird?
- Wenn Online-Zugang für Nutzer deaktiviert ist
- auch wenn kein Kennwort per Mail versandt werden soll, also nur wenn das Kennwort per Mail versandt werden soll?

_____________________________
Bug fixed: No password validation if online access is not activated for users.

When should it be possible that no e-mail address is stored?
- If online access is deactivated for users
- even if no password is to be sent by e-mail, i.e. only if the password is to be sent by e-mail?

**Comment by Larian77** [comment]
@375michael40veit 

Danke, kam leider bisher nicht selber dazu mich zu kümmern. Wir haben bei uns Nutzer, die einfach keine Mail haben bzw. diese nicht angeben wollen. Es sollte immer möglich sein, dass ein User keine mail angibt. In dem Fall sollte dann einfach für den User die Möglichkeit sich sein PW per Mail zurückzusetzen nicht vorhanden sein (während es für Benutzer mit Mail weiter funktioniert).

Thanks, unfortunately I haven't got round to doing it myself yet. We have users who simply don't have an e-mail or don't want to enter it. It should always be possible for a user not to enter an email. In this case, the user should simply not be able to reset their PW by email (while it continues to work for users with email).
