### ISSUE TITLE
Medien-Suchfenster funktioniert nicht

### ISSUE THREAD

**Issue by reinhard-mueller** [Larian77/Openbiblio#64]
Die als Pop-Up-Fenster geöffnete Mediensuche funktioniert bei mir überhaupt nicht zufriedenstellend, beispielsweise auf `circ/checkin_form.php` bei der Eingabe eines Suchbegriffs unter "Mediennummer" und Klick auf "Suche":
* Das geöffnete Fenster zeigt die (unbefüllte) Suchmaske statt der Suchergebnisse
* Das geöffnete Fenster hat ein komplettes Seitenlayout mit Logo usw.
* Selbst wenn man dann in der Suchmaske nochmal den Suchbegriff eingibt, ist die Auswahl des gewünschten Mediums und der Rücksprung in die Hauptmaske alles andere als intuitiv.

Ich denke, da ist mal was kaputtgegangen, was bisher nicht bemerkt wurde.

**Comment by Larian77** [comment]
Meinst du die Suche nach Medien oder Vorbestellungen im Benutzer? (Bibliothekarsoberfläche)

Unter https://openbiblio.de/openbiblio/home/index.php hat bei mir gerade alles funktioniert (test/tester). Oder mal bitte genau beschreiben wo es bei dir hängt :-)

**Comment by reinhard-mueller** [comment]
Am einfachsten so:
Ausleihe - Medienrückgabe - bei "Mediennummer" einen Text eingeben und den blauen Link "Suche" direkt neben der Eingabe klicken.

Meine Erwartung wäre, dass sich dann ein Fenster mit einer Liste von gefundenen Medien öffnet, aus denen ich eines auswählen kann.

**Comment by Larian77** [comment]
Nein, die Medienrückgabe funktioniert eigentlich schon immer nur über die Mediennummer. Das ist ja der Ort, wo der Bibliothekar der Reihe nach die rückgegebenen Medien einscannt und diese zurück gebucht werden, hier macht eine freie Suche eigentlich auch keinen Sinn.

**Comment by reinhard-mueller** [comment]
Das war nur ein Beispiel, wo diese Suchfunktion aufrufbar ist, die selbe findest du z.B. auch auf https://openbiblio.de/openbiblio/circ/mbr_view.php?mbrid=513 unter "Medienausleihe" und "Vorbestellen". Beide Male das selbe Schema, neben dem Eingabefeld für die Mediennummer ein Link zur Suche, wenn man die Nummer nicht weiß.

Ob das sinnvoll ist oder nicht, ist für mich hier gar nicht das Thema, irgendjemand hat's jedenfalls mal für sinnvoll angesehen und implementiert. Ich denke aber jedenfalls, wenn ein solcher Suchlink vorhanden ist, sollte er entweder funktionieren, oder er sollte entfernt werden.

**Comment by reinhard-mueller** [comment]
Hmmm.... nach ein bisschen Rumspielen mit der Maske bin ich glaube ich draufgekommen, wie das funktioniert: der Link öffnet offenbar wirklich absichtlich ein nicht-vorausgefülltes Suchfenster, in dem man dann suchen muss, und das gewünschte Medium kann dann über einen von zwei Links entweder in die Rückgabe oder die Vorreservierung übernommen werden.

Das ist zwar nicht direkt intuitiv, aber zumindest scheint es kein Fehler zu sein, daher schließe ich dieses Issue wieder.

**Comment by Larian77** [comment]
Ja, genau, das meinte ich oben und genau so ist es auch erstmal gedacht, dass man hier zum vorbestellen oder ausleihen ein Medium suchen kann. Schön ist das Ganze in der Tat nicht, aber es erfüllt seinen Zweck - sollte aber irgendwann auf alle Fälle mal mit überarbeitet werden :-)
