### ISSUE TITLE
Dauer des Passwort-Rücksetz-Link / Duration of the password reset link 

### ISSUE THREAD

**Issue by Larian77** [Larian77/Openbiblio#88]
Wenn ich als Dauer des Passwort-Rücksetz-Link 48 h setze, wird ja in der entsprechenden SQL-Tabelle der Wert "5" gespeichert.
In den Mails, die nun rausgehen, steht dann aber auch, dass man 5 h Zeit hätte. 
@375michael40veit da du die Stelle glaube am besten kennst: ist das nur ein Fehler beim Mail versenden (dass er den Index-Wert statt den wirklich Wert verwendet) oder wird auch der Rücksetz-Link nach 5h statt 48h gelöscht?

If I set the duration of the password reset link to 48 hours, the value “5” is saved in the corresponding SQL table.
However, the emails that go out now also say that you have 5 hours. 
@375michael40veit as I think you know the place best: is this just an error when sending the mail (that it uses the index value instead of the real value) or is the reset link also deleted after 5h instead of 48h?

**Comment by 375michael40veit** [comment]
Ich sehe es mir morgen mal an.
________________________________________________
I'll have a look at it tomorrow.

**Comment by 375michael40veit** [comment]
bug is fixed #90
